import React, { StrictMode } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
const API = import.meta.env.VITE_API_URL || 'http://localhost:3000';
const services = [
  ['01', 'Operating model design', 'Turn strategic intent into clear, shared ways of working—so every team knows what must be consistent and where it can move independently.'],
  ['02', 'Digital foundation', 'Shape the data, platforms, and core workflows that make dependable execution a capability, not a heroic effort.'],
  ['03', 'Modular growth', 'Create composable services and decision boundaries that help new ideas reach the market without destabilising the core.']
];
function App() {
  const submit = async (event) => { event.preventDefault(); const form = event.currentTarget; const button = form.querySelector('button'); button.disabled = true; button.textContent = 'Sending…'; const data = Object.fromEntries(new FormData(form)); try { const r = await fetch(`${API}/api/enquiries`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); if (!r.ok) throw new Error(); form.reset(); button.textContent = 'Message received'; } catch { button.textContent = 'Try again'; alert('We could not send your message. Please try again shortly.'); } finally { setTimeout(() => { button.disabled = false; button.textContent = 'Start a conversation'; }, 2500); } };
  return <><header><a className="brand" href="#top">ETHER<span>TRIX</span></a><nav><a href="#services">What we do</a><a href="#approach">Our approach</a><a className="nav-cta" href="#contact">Let’s talk</a></nav></header><main id="top"><section className="hero"><p className="eyebrow">ENTERPRISE ARCHITECTURE, MADE USEFUL</p><h1>Make your operating model <em>work</em> harder.</h1><p className="lede">Ethertrix helps ambitious organisations build the shared foundations that make execution reliable—and growth less fragile.</p><a className="button" href="#contact">Build your foundation <span>→</span></a><div className="hero-mark"><i></i><i></i><i></i><b>EXECUTE<br/>ADAPT<br/>GROW</b></div></section><section className="statement"><p>Strategy only becomes real when your people, processes, data, and technology can move together.</p><div><span>ETHERTRIX VIEW</span><strong>Clarity at the core. Freedom at the edge.</strong></div></section><section id="services" className="services"><div className="section-head"><p className="eyebrow">CAPABILITIES</p><h2>Design the system behind better decisions.</h2></div><div className="service-grid">{services.map(([n,t,d]) => <article key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p><a href="#contact">Explore <b>↗</b></a></article>)}</div></section><section id="approach" className="approach"><div><p className="eyebrow">HOW WE WORK</p><h2>A stable core is not the enemy of change. It is what lets change travel.</h2></div><div className="steps"><p><span>01</span> Find the few capabilities that must be exceptional.</p><p><span>02</span> Decide what must be shared, and what should stay flexible.</p><p><span>03</span> Turn those choices into a practical roadmap teams can execute.</p></div></section><section className="outcomes"><p className="eyebrow">THE OUTCOME</p><div><h2>Less reinvention.<br/><em>More momentum.</em></h2><p>We connect executive ambition to the operating realities that determine whether it succeeds. The result is an enterprise that can deliver consistently while making room for its next opportunity.</p></div></section><section id="contact" className="contact"><div><p className="eyebrow">START A CONVERSATION</p><h2>What would move faster if your foundation was stronger?</h2><p>Tell us where execution is getting stuck. We’ll start with a focused conversation.</p></div><form onSubmit={submit}><label>Name<input name="name" required minLength="2" /></label><label>Work email<input name="email" type="email" required /></label><label>Company<input name="company" required minLength="2" /></label><label>Your challenge<textarea name="challenge" required minLength="10" placeholder="What are you trying to make possible?"></textarea></label><button className="button" type="submit">Start a conversation <span>→</span></button></form></section></main><footer><a className="brand" href="#top">ETHER<span>TRIX</span></a><p>Architecture for execution.</p><p>© {new Date().getFullYear()} Ethertrix</p></footer></>;
}
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>);
